# Generated by Django 5.1.3 on 2024-11-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "price_history_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={"db_table": "price_history", "managed": False,},
        ),
        migrations.CreateModel(
            name="YieldUnit",
            fields=[
                ("yield_unit_id", models.AutoField(primary_key=True, serialize=False)),
                ("yield_unit", models.CharField(max_length=50)),
            ],
            options={"db_table": "yield_unit", "managed": False,},
        ),
    ]
