# Generated by Django 5.1.3 on 2024-11-20 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="farmer", old_name="first_name", new_name="name",
        ),
        migrations.RemoveField(model_name="farmer", name="last_name",),
    ]
