# Generated by Django 5.1.2 on 2024-10-16 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_lab"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                ("crop_id", models.AutoField(primary_key=True, serialize=False)),
                ("crop_name", models.CharField(max_length=255)),
                (
                    "farmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.farmer"
                    ),
                ),
            ],
        ),
    ]
