# Generated by Django 5.1.2 on 2024-10-16 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_crop"),
    ]

    operations = [
        migrations.CreateModel(
            name="FieldHistory",
            fields=[
                ("field_hist_id", models.AutoField(primary_key=True, serialize=False)),
                ("plant_date", models.DateField()),
                ("harvest_date", models.DateField()),
                ("yield_amount", models.FloatField()),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.crop"
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.field"
                    ),
                ),
            ],
        ),
    ]
