# Generated by Django 5.1.2 on 2024-10-16 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_fieldhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="SoilTest",
            fields=[
                ("soil_id", models.AutoField(primary_key=True, serialize=False)),
                ("test_date", models.DateField()),
                ("ph", models.FloatField()),
                ("salts", models.FloatField()),
                ("chlorides", models.FloatField()),
                ("sodium", models.FloatField()),
                ("cec", models.FloatField()),
                ("excess_lime", models.FloatField()),
                ("organic_matter", models.FloatField()),
                ("organic_n", models.FloatField()),
                ("ammonium_n", models.FloatField()),
                ("nitrate_n", models.FloatField()),
                ("phosphorus", models.FloatField()),
                ("potassium_ppm", models.FloatField()),
                ("potassium_meq_per_100g", models.FloatField()),
                ("calcium_ppm", models.FloatField()),
                ("calcium_meq_per_100g", models.FloatField()),
                ("magnesium_ppm", models.FloatField()),
                ("magnesium_meq_per_100g", models.FloatField()),
                ("sulfate", models.FloatField()),
                ("zinc", models.FloatField()),
                ("iron", models.FloatField()),
                ("manganese", models.FloatField()),
                ("copper", models.FloatField()),
                ("boron", models.FloatField()),
                ("recom_nitrogen", models.FloatField()),
                ("recom_phos", models.FloatField()),
                ("recom_potash", models.FloatField()),
                ("recom_calcium", models.FloatField()),
                ("recom_magnesium", models.FloatField()),
                ("recom_sulphur", models.FloatField()),
                ("recom_zinc", models.FloatField()),
                ("recom_iron", models.FloatField()),
                ("recom_manganese", models.FloatField()),
                ("recom_copper", models.FloatField()),
                ("recom_boron", models.FloatField()),
                ("recom_gypsum", models.FloatField()),
                ("recom_lime", models.FloatField()),
                (
                    "crop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.crop"
                    ),
                ),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.field"
                    ),
                ),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.lab"
                    ),
                ),
            ],
        ),
    ]
