# Generated by Django 5.1.2 on 2024-10-18 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_soiltest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fertilizer_application", "Fertilizer Application"),
                            ("seeding_new_crop", "Seeding New Crop"),
                            ("irrigation", "Irrigation"),
                            ("herbicide_application", "Herbicide Application"),
                            ("pesticide_application", "Pesticide Application"),
                            ("harvest", "Harvest"),
                            ("mechanical_disturbance", "Mechanical Disturbance"),
                            ("weather", "Weather"),
                            ("livestock", "Livestock"),
                            ("management", "Management"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text", models.TextField(blank=True, default="")),
                ("year", models.PositiveIntegerField(default=2024)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"unique_together": {("category", "year")},},
        ),
    ]
